# Generated by Django 4.1.5 on 2023-01-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_remove_user_followers_user_birthday_user_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="sex",
            new_name="gender",
        ),
    ]
